
name: Test Without QR Enabled

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'

    steps:
      - uses: actions/checkout

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip3 install .

      - name: Install test dependencies
        run: |
          pip3 install pytest coverage pytest-cov pytest-randomly mock-open

      - name: Test with pytest
        run: |
          pytest --cov=wireguard --cov-branch --cov-report term-missing --verbose -rsxX --disable-pytest-warnings tests
